config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :organizers
  get "/tournaments/my" => "tournaments#my", as: 'my_tournaments'
  get "/tournaments/:id" => "tournaments#show", as: 'tournament'
  get "/tournaments/:id/embed" => "tournaments#embed", as: 'embed_tournament'
  post "/tournaments/:id/subscribe" => "tournaments#subscribe", as: 'subscribe_tournament'
  get "/tournaments/unsubscribe/:token" => "tournaments#unsubscribe", as: 'unsubscribe_tournament'
  namespace :api do
    namespace :v1 do
      resources :tournaments do
      end
      post 'auth' => "auth#create"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "main#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :participants, dependent: :destroy
  accepts_nested_attributes_for :participants

  belongs_to :phase
  validates_presence_of :from, :until, :place, :phase
  validate do
    unless self.from < self.until
      self.errors.add(:until, "must be after from")
    end
  end
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tournaments

  def to_s
    email
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :match
  validates_numericality_of :result, allow_nil: true
  validates_presence_of :name, :match
  def to_s
    name
  end
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :tournament
  has_many :matches, dependent: :destroy
  accepts_nested_attributes_for :matches

  validates_presence_of :tournament, :name, :from, :until
  validate do
    unless self.from && self.until && self.from < self.until
      self.errors.add(:until, "must be after from")
    end
  end

  def to_s
    name
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :phases
  has_many :matches, through: :phases
  has_many :participants, through: :matches
  has_many :tournament_subscriptions
  validates_presence_of :name, :secret_token
  before_validation do
    self.set_token
  end

  def to_s
    name
  end

  protected
  def set_token
    self.secret_token ||= SecureRandom.hex(16)
  end
end

app/models/tournament_subscription.rb
class TournamentSubscription < ApplicationRecord
  belongs_to :tournament
  validates_presence_of :tournament, :email, :unsubscribe_token
  validates_uniqueness_of :email, scope: :tournament
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  before_validation do
    self.unsubscribe_token ||= SecureRandom.hex(16)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::Base

end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < Api::V1::ApiController
  def create
    organizer = Organizer.find_for_database_authentication(email: params[:email])
    if organizer && organizer.valid_password?(params[:password])
      render json: payload(organizer)
    else
      render json: {errors: ['Invalid Email/Password']}, status: :unauthorized
    end
  end

  private

  def payload(organizer)
    return nil unless organizer and organizer.id
    {
      auth_token: encode({organizer_id: organizer.id}),
      organizer: {id: organizer.id, email: organizer.email}
    }
  end


  def encode(payload, expiration = nil)
    expiration ||= Rails.application.secrets.jwt_expiration_hours

    payload = payload.dup
    payload['exp'] = expiration.to_i.hours.from_now.to_i

    JWT.encode payload, Rails.application.secrets.jwt_secret
  end
end

app/controllers/api/v1/tournaments_controller.rb
class Api::V1::TournamentsController < Api::V1::ApiController
  before_action :authenticate_organizer!
  def create
    organizer = current_organizer
    begin
      par = params.require(:tournament) 
      unless (id = params[:tournament].delete(:id)) && @tournament = organizer.tournaments.where(id: id).first
        @tournament = organizer.tournaments.build
      end
      Tournament.transaction do 
        %w(name location).each do |key|
          @tournament.send("#{key}=", par[key])
        end
        @tournament.save!
        @tournament.phases.destroy_all
        par.require(:phases)
        par[:phases].each do |phase_par|
          phase = @tournament.phases.create!(phase_par.slice(:name, :from, :until).permit!)
          phase_par[:matches]&.each do |match_par|
            match_par.require([:from, :until, :place])
            match = phase.matches.create!(match_par.slice(:from, :until, :place).permit!)
            match_par[:participants]&.each do |participant|
              participant.require(:name)
              match.participants.create! participant.slice(:name, :result).permit!
            end
          end
        end
      end
      @tournament.tournament_subscriptions.each do |sub|
        TournamentMailer.update_email(Tournament.first, sub.email, sub.unsubscribe_token).deliver_later
      end
      render json: { tournament: {id: @tournament.id, link: url_for(tournament_path(id: @tournament.secret_token))}}
    rescue ActiveRecord::RecordInvalid => e
      render json: {error: {e.record.class.name.downcase => e.record.errors}}, status: :unprocessable_entity 
    rescue ActionController::ParameterMissing => e
      render json: {error: e.to_s}, status: :unprocessable_entity 
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    if current_organizer
      redirect_to my_tournaments_path
    else
      render
    end
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_organizer!, only: [:my]
  def show
    @tournament = Tournament.where(secret_token: params[:id]).first!
    @participant_filter = params[:participant_filter]
  end

  def embed
    @tournament = Tournament.where(secret_token: params[:id]).first!
    response.headers.delete "X-Frame-Options"
    render layout: 'embedded'
  end

  def my
    @tournaments = current_organizer.tournaments
  end
  def subscribe
    @tournament = Tournament.where(secret_token: params[:id]).first!
    @tournament_subscription = TournamentSubscription.new
    @tournament_subscription.tournament = @tournament
    @tournament_subscription.email = params[:email]
    if @tournament_subscription.save
      redirect_to tournament_path(id: @tournament.secret_token), flash: {notice: "Successfully subscribed"}
    else
      @tournament_subscription.errors.full_messages.each do |e|
        flash[:alert]= e
      end
      redirect_to tournament_path(id: @tournament.secret_token)
    end
  end
  def unsubscribe
    @tournament = Tournament.where(secret_token: params[:token]).first!
    @tournament_subscription = @tournament.tournament_subscriptions.where(unsubscribe_token: params[:unsubscribe_token]).first!
    @tournament_subscription.destroy
    redirect_to tournament_path(id: @tournament.secret_token), flash: {notice: "Sucessfully unsubscribed"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def filter_link(participant)
    if participant
      link_to participant.name, tournament_path(@tournament.secret_token, participant_filter: participant.name)
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Kandanda"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = render partial: 'shared/nav'
    .row
      .small-12.columns
        = render partial: 'shared/flash'
    #main.row
      .small-12.columns
        = yield
    #footer
      .row
        .small-12.columns
          ul.menu
            li
              b= link_to "Download Client", "https://github.com/kandanda/Client/releases"
            li
              = link_to "Client Project", "https://github.com/kandanda/Client"
            li
              = link_to "Server Project", "https://github.com/kandanda/Server"

app/views/layouts/embedded.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Kandanda"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
  body
    .row
      .small-12.columns
        = yield
    .row
      .small-12.columns
        = link_to "Powered by Kandanda", "https://www.kandanda.ch"

app/views/main/home.html.slim
.row
  .small-12.large-12.columns
    h1 Welcome to Kandanda!
    hr
.row
  .large-4.column.large-offset-4.small-12
    = image_tag "kandanda_logo", class: 'logo'
.row
  .small-12.column.large-6.large-offset-3
    .panel.callout
      = link_to "Sign Up to start publishing your tournaments on Kandanda", new_organizer_registration_path, class: "button large"

app/views/shared/_flash.slim
- flashes = {:notice => 'success', :alert => 'warning', :error => 'alert', :secondary => 'secondary'}
- flashes.each do |key, value|
  - if flash[key]
    .callout data = { closable: '' } class=value
      = flash[key]
      button class="close-button" aria-label="Dismiss alert" type="button" data-close=''
       span aria-hidden="true" &times;

app/views/shared/_google_maps.html.slim
iframe width="400" height="250" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=#{Rails.application.secrets.google_maps_key}&q=#{location}" allowfullscreen

app/views/shared/_nav.html.slim
.title-bar(data-responsive-toggle="main-menu" data-hide-for="medium")
  button.menu-icon(type='button' data-toggle=true)
#main-menu.top-bar data= {topbar: true, options: "is_hover:false"}
  .top-bar-left
    ul.dropdown.menu(data-dropdown-menu=true)
      li= link_to "Kandanda", root_path
      li= link_to "Meine Turniere", my_tournaments_path
  .top-bar-right
    ul.menu(data-responsive-menu="drilldown medium-dropdown")
      - if current_organizer
        li.has-submenu
          a href= '#' Logged in as #{current_organizer}
          ul.submenu.menu.vertical
            li= link_to "Sign Out", destroy_organizer_session_path, method: :delete
      - else
        li= link_to "Sign In", new_organizer_session_path

app/views/tournaments/embed.html.slim
.row
  .large-6.columns
    h1= @tournament
.row
  .large-12.columns
    - num_pars = @tournament.phases.map{|r| r.matches.map{|m| m.participants.count}.max||0}.max
    - @tournament.phases.order(:from).each do |phase|
      h2
        =phase
        small
          =<> l phase.from
          |-
          =< l phase.until
      table.table
        tr
          - num_pars.times do |i|
            th
            th
          th Anfang
          th Ende
          th Where
        - phase.matches.each do |match|
          tr
            td = match.participants.first
            - match.participants.each do |p|
              td
                - if p.result
                  b=< "(#{p.result})"
            td = match.participants.last
            td= l match.from
            td= l match.until
            td= match.place

app/views/tournaments/my.html.slim
h1 My Tournaments
- if @tournaments.size > 0
  - @tournaments.each do |t|
    .panel.callout
      h2=link_to t, tournament_path(t.secret_token)
      ul
        - t.participants.pluck(:name).sort.uniq.first(6).each do |pname|
          li= pname
- else
  p You do not currently have any tournaments. Try uploading one through the client.

app/views/tournaments/show.html.slim
.row
  .large-6.columns
    h1= @tournament
    = form_tag(subscribe_tournament_path(id: @tournament.secret_token), class: 'custom') do
      .input-group
        span.input-group-label @
        = text_field_tag :email, "", placeholder: "Your E-Mail", class: "input-group-field"
        .input-group-button
          = submit_tag "Subscribe for Updates", name: nil, class: 'button postfix'


  .large-6.columns
    - unless @tournament.location.blank?
      = render partial: "shared/google_maps", locals: {location: @tournament.location}

.row
  .large-12.columns
    - if @participant_filter
      .callout.secondary
        p
          | Only showing matches for
          b=< @participant_filter
        p= link_to "show all", tournament_path(id: @tournament.secret_token)
    - num_pars = @tournament.phases.map{|r| r.matches.map{|m| m.participants.count}.max||0}.max
    - @tournament.phases.order(:from).each do |phase|
      h2
        =phase
        small
          =<> l phase.from
          |-
          =< l phase.until
      table.table
        tr
          - num_pars.times do |i|
            th
            th
          th Anfang
          th Ende
          th Where
        - matches = @participant_filter ? phase.matches.joins(:participants).where(participants: {name: @participant_filter}) : phase.matches
        - matches.each do |match|
          tr
            td = filter_link match.participants.first
            - match.participants.each do |p|
              td
                - if p.result
                  b=< "(#{p.result})"
            td = filter_link match.participants.last
            td= l match.from
            td= l match.until
            td= match.place

.row
  .large-12.columns
    h3 Embedding
    p Add this snippet to your website to display the tournament schedule
    textarea
      = %Q(<iframe width="1170" height="800" src="#{embed_tournament_url(@tournament.secret_token)}" frameborder="0" ></iframe>)